# Use an official PostgreSQL image as a parent image
FROM postgres:13

# Environment variables
ENV POSTGRES_DB=attendence
ENV POSTGRES_USER=root
ENV POSTGRES_PASSWORD=root

# Expose the PostgreSQL port
EXPOSE 5432
